steps:
  # 1. Build the Docker image tarball using Nix
  - name: 'nixos/nix:latest'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        nix build . --extra-experimental-features 'nix-command flakes'
        # Follow the symlink and copy the actual file to /workspace
        cp $(readlink -f result) python-multi.tar.gz
    id: 'nix-build'

  # 2. Load the resulting tarball into the local Docker daemon
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker load < python-multi.tar.gz
    id: 'docker-load'

  # 3. Tag the image for Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'tag'
      - 'python-multi-nix:latest'
      - '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/python-multi-nix:${_TAG}'
    id: 'docker-tag'

  # 4. Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/python-multi-nix:${_TAG}'
    id: 'docker-push'

substitutions:
  _LOCATION: 'us-central1'
  _REPOSITORY: 'images'
  _TAG: 'latest'

timeout: 7200s  # 2 hours

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
